### ISSUE TITLE
Нет вьюхи error

### ISSUE THREAD

**Issue by andrewQwer** [max-kudosh/chat#1]
В случае ошибки рендерится вьюха error
```javascript
app.use(function (err, req, res, next) {
    res.status(err.status || 500);
    res.render('error', {
        message: err.message,
        error: {}
    });
});
```
Но в списке вьюх ее нет и в случае ошибки получаю такое
![image](https://cloud.githubusercontent.com/assets/710513/7681531/a958af32-fd79-11e4-81c2-526570353b52.png)

**Comment by max-kudosh** [comment]
добавил вьюху для ошибок
