### ISSUE TITLE
Не работает логин

### ISSUE THREAD

**Issue by andrewQwer** [max-kudosh/chat#3]
Не могу залогиниться, т.к. нет юзеров и node пытается отрендерить вьюху error. Опытным путем установлено, что  Promise is not defined

**Comment by max-kudosh** [comment]
Хм, а какая у тебя версия нода?
Насколько я понял, промисы были добавлены в версии 0.11.13.

**Comment by andrewQwer** [comment]
возможно нода устарела, попробую обновить

**Comment by andrewQwer** [comment]
после обновления ноды все заработало
